import type { Metadata } from "next";
import { Link } from "@/i18n/navigation";
import { getTranslations, setRequestLocale } from "next-intl/server";
import { buildMetadata } from "@/lib/seo";
import { Header, Footer, RelatedTools } from "@/components/Layout";
import { JsonLd } from "@/components/JsonLd";
import { Breadcrumbs } from "@/components/Breadcrumbs";
import EmDashRemoverTool from "@/components/EmDashRemoverTool";

const siteUrl = "https://sluggenerator.app";
const path = "/em-dash-remover";

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale } = await params;
  setRequestLocale(locale);
  const t = await getTranslations({ locale, namespace: "pages.emDashRemover" });
  return buildMetadata({ title: t("title"), description: t("description"), path, locale });
}

export default async function EmDashRemover({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale } = await params;
  setRequestLocale(locale);
  const t = await getTranslations("pages.emDashRemover");

  const toolLd = {
    "@context": "https://schema.org",
    "@type": "WebApplication",
    name: "Em Dash Remover",
    url: `${siteUrl}${path}`,
    description:
      "Remove or replace em dashes (—) in text with commas, hyphens, spaces, or periods. Free online punctuation cleanup tool.",
    applicationCategory: "WebApplication",
    operatingSystem: "Any",
    offers: { "@type": "Offer", price: "0", priceCurrency: "USD" },
  };

  return (
    <div className="flex flex-col min-h-screen">
      <JsonLd data={toolLd} />
      <Header />
      <main className="flex-1 px-4 py-12">
        <div className="max-w-5xl mx-auto">
          <Breadcrumbs items={[{ name: "Em Dash Remover" }]} />
          <div className="text-center mb-10">
            <h1 className="text-4xl md:text-5xl font-bold text-gray-900 mb-4">{t("h1")}</h1>
            <p className="text-lg text-gray-600 max-w-2xl mx-auto">{t("subtitle")}</p>
          </div>

          <EmDashRemoverTool placeholder={t("placeholder")} />

          {locale === "en" && (
            <section className="w-full max-w-3xl mx-auto mt-16 prose prose-gray">
              <h2>What Is an Em Dash?</h2>
              <p>
                An em dash (—, U+2014) is a punctuation mark roughly the width of the
                letter &ldquo;M&rdquo;. Writers use it to set off parenthetical phrases, mark
                interruptions, or replace colons. It is different from the en dash
                (–, U+2013), used for ranges like &ldquo;pages 10–25&rdquo;, and the plain
                hyphen (-), used to join words.
              </p>

              <h2>Why Remove Em Dashes?</h2>
              <ul>
                <li>
                  <strong>House style</strong> — many style guides prefer commas,
                  parentheses, or periods over em dashes, or require spaced en dashes
                  instead.
                </li>
                <li>
                  <strong>Plain-text environments</strong> — em dashes can render
                  inconsistently in terminals, code comments, CSV files, and legacy
                  systems that expect ASCII.
                </li>
                <li>
                  <strong>Editing AI-drafted text</strong> — text generated by writing
                  assistants often leans heavily on em dashes. If the punctuation
                  density doesn&apos;t match your voice, normalizing the dashes is a quick
                  cleanup step.
                </li>
                <li>
                  <strong>Data processing</strong> — when text feeds into slugs, IDs,
                  or search indexes, typographic dashes cause mismatches that plain
                  hyphens avoid.
                </li>
              </ul>

              <h2>How This Tool Works</h2>
              <p>
                Paste your text and pick a replacement strategy. The tool counts every
                em dash (including the horizontal bar ― and two/three-em dashes) and
                rewrites them in one pass:
              </p>
              <ul>
                <li>
                  <strong>Comma</strong>: <code>results — far beyond hopes — came in</code>{" "}
                  → <code>results, far beyond hopes, came in</code>
                </li>
                <li>
                  <strong>Hyphen</strong>: <code>word — word</code> → <code>word - word</code>
                </li>
                <li>
                  <strong>Period</strong>: splits the clause into two sentences and
                  capitalizes the next word
                </li>
                <li>
                  <strong>Space / Remove</strong>: for minimal cleanup
                </li>
              </ul>
              <p>
                Toggle <em>Also en dashes</em> to normalize range dashes in the same
                pass. Everything runs locally in your browser — no text is uploaded.
              </p>

              <h2>Em Dash vs En Dash vs Hyphen</h2>
              <div className="overflow-x-auto">
                <table>
                  <thead>
                    <tr>
                      <th>Mark</th>
                      <th>Unicode</th>
                      <th>Typical use</th>
                    </tr>
                  </thead>
                  <tbody>
                    <tr>
                      <td>Em dash (—)</td>
                      <td>U+2014</td>
                      <td>Breaks in thought, parenthetical phrases</td>
                    </tr>
                    <tr>
                      <td>En dash (–)</td>
                      <td>U+2013</td>
                      <td>Ranges (2010–2020), connections (Boston–London)</td>
                    </tr>
                    <tr>
                      <td>Hyphen (-)</td>
                      <td>U+002D</td>
                      <td>Compound words, URL slugs, code</td>
                    </tr>
                  </tbody>
                </table>
              </div>

              <h2>FAQ</h2>
              <h3>Does this change my text in any other way?</h3>
              <p>
                No. Only dash characters are touched. Quotes, spacing elsewhere, and
                all other punctuation stay exactly as you pasted them.
              </p>
              <h3>Is my text sent to a server?</h3>
              <p>
                No. All processing happens locally in your browser. Your text never
                leaves your device.
              </p>

              <h2>Related Tools</h2>
              <p>
                Need broader cleanup? The{" "}
                <Link href="/plain-text-converter">Plain Text Converter</Link> strips
                HTML, smart quotes, and invisible characters in one pass. Check for
                hidden Unicode with the{" "}
                <Link href="/invisible-character-detector">Invisible Character Detector</Link>,
                or turn clean text into URL slugs with the{" "}
                <Link href="/url-slug-generator">URL Slug Generator</Link>.
              </p>
            </section>
          )}

          {locale === "ja" && (
            <section className="w-full max-w-3xl mx-auto mt-16 prose prose-gray">
              <h2>EMダッシュとは？</h2>
              <p>EMダッシュ（—、U+2014）は、文字「M」とほぼ同じ幅の約物です。挿入句の区切り、文の中断、コロンの代用として使われます。範囲を示すENダッシュ（–、U+2013、例：10–25ページ）や、単語をつなぐハイフン（-）とは異なる文字です。</p>
              <h2>EMダッシュを削除する理由</h2>
              <ul>
                <li><strong>表記ルールの統一</strong> — 多くのスタイルガイドはEMダッシュよりも読点や括弧を推奨しています。</li>
                <li><strong>プレーンテキスト環境</strong> — ターミナル、コードコメント、CSVファイル、ASCII前提のレガシーシステムでは表示が乱れることがあります。</li>
                <li><strong>AI生成テキストの編集</strong> — ライティングアシスタントが生成した文章はEMダッシュを多用しがちです。自分の文体に合わせる場合の整形に便利です。</li>
                <li><strong>データ処理</strong> — スラッグやID、検索インデックスに流す場合、約物のダッシュは不一致の原因になります。</li>
              </ul>
              <h2>使い方</h2>
              <p>テキストを貼り付けて置換方法を選ぶだけです。EMダッシュ（水平バー ― や2倍・3倍ダッシュを含む）をすべてカウントし、一括で変換します。読点・ハイフン・ピリオド・スペース・完全削除から選べます。「Also en dashes」をオンにするとENダッシュも同時に正規化されます。</p>
              <p>処理はすべてブラウザ内で完結し、テキストがサーバーに送信されることはありません。</p>
              <h2>関連ツール</h2>
              <p>より広い整形には<Link href="/plain-text-converter">Plain Text Converter</Link>を、不可視文字の検出には<Link href="/invisible-character-detector">Invisible Character Detector</Link>を、URLスラッグ生成には<Link href="/url-slug-generator">URL Slug Generator</Link>をどうぞ。</p>
            </section>
          )}

          {locale === "de" && (
            <section className="w-full max-w-3xl mx-auto mt-16 prose prose-gray">
              <h2>Was ist ein Geviertstrich (Em Dash)?</h2>
              <p>Der Geviertstrich (—, U+2014) ist ein Satzzeichen, das etwa so breit ist wie der Buchstabe &bdquo;M&ldquo;. Er markiert Einschübe, Unterbrechungen oder ersetzt Doppelpunkte. Er unterscheidet sich vom Halbgeviertstrich (–, U+2013, für Bereiche wie &bdquo;Seite 10–25&ldquo;) und vom Bindestrich (-).</p>
              <h2>Warum Geviertstriche entfernen?</h2>
              <ul>
                <li><strong>Hausstil</strong> — viele Styleguides bevorzugen Kommas, Klammern oder den deutschen Halbgeviertstrich mit Leerzeichen.</li>
                <li><strong>Plain-Text-Umgebungen</strong> — in Terminals, Code-Kommentaren, CSV-Dateien und ASCII-basierten Systemen werden sie oft falsch dargestellt.</li>
                <li><strong>KI-Texte überarbeiten</strong> — von Schreibassistenten erzeugte Texte verwenden oft auffällig viele Geviertstriche. Die Normalisierung ist ein schneller Bereinigungsschritt.</li>
                <li><strong>Datenverarbeitung</strong> — bei Slugs, IDs oder Suchindizes verursachen typografische Striche Abweichungen.</li>
              </ul>
              <h2>So funktioniert das Tool</h2>
              <p>Text einfügen, Ersetzungsstrategie wählen. Das Tool zählt alle Geviertstriche (inklusive Horizontalbalken ― und Doppel-/Dreifachstriche) und ersetzt sie in einem Durchgang durch Komma, Bindestrich, Punkt, Leerzeichen oder entfernt sie ganz. Mit &bdquo;Also en dashes&ldquo; werden auch Halbgeviertstriche normalisiert.</p>
              <p>Die gesamte Verarbeitung läuft lokal im Browser — kein Text wird hochgeladen.</p>
              <h2>Verwandte Tools</h2>
              <p>Für umfassendere Bereinigung: <Link href="/plain-text-converter">Plain Text Converter</Link>. Versteckte Unicode-Zeichen findet der <Link href="/invisible-character-detector">Invisible Character Detector</Link>. Saubere URL-Slugs erstellt der <Link href="/url-slug-generator">URL Slug Generator</Link>.</p>
            </section>
          )}

          {locale === "es" && (
            <section className="w-full max-w-3xl mx-auto mt-16 prose prose-gray">
              <h2>¿Qué es la raya (em dash)?</h2>
              <p>La raya (—, U+2014) es un signo de puntuación con el ancho aproximado de la letra &ldquo;M&rdquo;. Se usa para marcar incisos, interrupciones o sustituir dos puntos. Es distinta del guion medio (–, U+2013, para rangos como &ldquo;páginas 10–25&rdquo;) y del guion corto (-).</p>
              <h2>¿Por qué eliminar las rayas?</h2>
              <ul>
                <li><strong>Estilo editorial</strong> — muchas guías de estilo prefieren comas, paréntesis o puntos en lugar de rayas.</li>
                <li><strong>Entornos de texto plano</strong> — en terminales, comentarios de código, archivos CSV y sistemas ASCII pueden mostrarse mal.</li>
                <li><strong>Editar texto generado por IA</strong> — los asistentes de escritura tienden a abusar de las rayas. Normalizarlas es una limpieza rápida.</li>
                <li><strong>Procesamiento de datos</strong> — en slugs, IDs o índices de búsqueda, los guiones tipográficos causan discrepancias.</li>
              </ul>
              <h2>Cómo funciona</h2>
              <p>Pega tu texto y elige una estrategia de reemplazo. La herramienta cuenta todas las rayas (incluida la barra horizontal ― y las rayas dobles/triples) y las convierte en un solo paso: coma, guion, punto, espacio o eliminación total. Activa &ldquo;Also en dashes&rdquo; para normalizar también los guiones medios.</p>
              <p>Todo se procesa localmente en tu navegador — tu texto nunca sale de tu dispositivo.</p>
              <h2>Herramientas relacionadas</h2>
              <p>Para una limpieza más amplia: <Link href="/plain-text-converter">Plain Text Converter</Link>. Detecta caracteres ocultos con el <Link href="/invisible-character-detector">Invisible Character Detector</Link>. Genera slugs limpios con el <Link href="/url-slug-generator">URL Slug Generator</Link>.</p>
            </section>
          )}

          {locale === "pt" && (
            <section className="w-full max-w-3xl mx-auto mt-16 prose prose-gray">
              <h2>O que é o travessão (em dash)?</h2>
              <p>O travessão (—, U+2014) é um sinal de pontuação com a largura aproximada da letra &ldquo;M&rdquo;. É usado para marcar apostos, interrupções ou substituir dois-pontos. É diferente do meia-risca (–, U+2013, para intervalos como &ldquo;páginas 10–25&rdquo;) e do hífen (-).</p>
              <h2>Por que remover travessões?</h2>
              <ul>
                <li><strong>Padrão editorial</strong> — muitos guias de estilo preferem vírgulas, parênteses ou pontos no lugar de travessões.</li>
                <li><strong>Ambientes de texto puro</strong> — em terminais, comentários de código, arquivos CSV e sistemas ASCII, eles podem ser exibidos incorretamente.</li>
                <li><strong>Editar texto gerado por IA</strong> — assistentes de escrita tendem a usar travessões em excesso. Normalizá-los é uma limpeza rápida.</li>
                <li><strong>Processamento de dados</strong> — em slugs, IDs ou índices de busca, traços tipográficos causam incompatibilidades.</li>
              </ul>
              <h2>Como funciona</h2>
              <p>Cole seu texto e escolha uma estratégia de substituição. A ferramenta conta todos os travessões (incluindo a barra horizontal ― e travessões duplos/triplos) e os converte de uma vez: vírgula, hífen, ponto, espaço ou remoção total. Ative &ldquo;Also en dashes&rdquo; para normalizar também as meias-riscas.</p>
              <p>Todo o processamento acontece localmente no navegador — seu texto nunca sai do dispositivo.</p>
              <h2>Ferramentas relacionadas</h2>
              <p>Para limpeza mais ampla: <Link href="/plain-text-converter">Plain Text Converter</Link>. Detecte caracteres ocultos com o <Link href="/invisible-character-detector">Invisible Character Detector</Link>. Gere slugs limpos com o <Link href="/url-slug-generator">URL Slug Generator</Link>.</p>
            </section>
          )}

          {locale === "fr" && (
            <section className="w-full max-w-3xl mx-auto mt-16 prose prose-gray">
              <h2>Qu&apos;est-ce que le tiret cadratin (em dash) ?</h2>
              <p>Le tiret cadratin (—, U+2014) est un signe de ponctuation d&apos;environ la largeur de la lettre « M ». Il marque les incises, les interruptions ou remplace les deux-points. Il diffère du tiret demi-cadratin (–, U+2013, pour les plages comme « pages 10–25 ») et du trait d&apos;union (-).</p>
              <h2>Pourquoi supprimer les tirets cadratins ?</h2>
              <ul>
                <li><strong>Charte éditoriale</strong> — de nombreux guides de style préfèrent les virgules, parenthèses ou points.</li>
                <li><strong>Environnements texte brut</strong> — terminaux, commentaires de code, fichiers CSV et systèmes ASCII peuvent mal les afficher.</li>
                <li><strong>Éditer du texte généré par IA</strong> — les assistants d&apos;écriture abusent souvent des tirets cadratins. Les normaliser est un nettoyage rapide.</li>
                <li><strong>Traitement de données</strong> — dans les slugs, IDs ou index de recherche, les tirets typographiques créent des incohérences.</li>
              </ul>
              <h2>Fonctionnement</h2>
              <p>Collez votre texte et choisissez une stratégie de remplacement. L&apos;outil compte tous les tirets cadratins (y compris la barre horizontale ― et les tirets doubles/triples) et les convertit en un seul passage : virgule, trait d&apos;union, point, espace ou suppression totale. Activez « Also en dashes » pour normaliser aussi les demi-cadratins.</p>
              <p>Tout le traitement s&apos;effectue localement dans votre navigateur — votre texte ne quitte jamais votre appareil.</p>
              <h2>Outils associés</h2>
              <p>Pour un nettoyage plus large : <Link href="/plain-text-converter">Plain Text Converter</Link>. Détectez les caractères cachés avec l&apos;<Link href="/invisible-character-detector">Invisible Character Detector</Link>. Générez des slugs propres avec le <Link href="/url-slug-generator">URL Slug Generator</Link>.</p>
            </section>
          )}

          <RelatedTools current={path} />
        </div>
      </main>
      <Footer />
    </div>
  );
}
