import type { Locale } from "@/i18n/routing";

export interface Article { title: string; description: string; body: string; }

export const meta = { slug: "clean-code-naming-principles", date: "2026-06-01", readTime: 5 };

const p = (l: Locale, path: string) => (l === "en" ? path : `/${l}${path}`);
const build = (l: Locale, t: Article): Article => ({
  ...t,
  body: t.body
    .replaceAll("%HUB%", p(l, "/case-converter-online")),
});

export const article: Record<Locale, Article> = {
  en: build("en", {
    title: "Clean Code Naming Principles: Lessons from Robert C. Martin",
    description: "Learn naming principles from Clean Code by Uncle Bob. Meaningful names, avoiding disinformation, and intention-revealing code.",
    body: `<p>Robert C. Martin's "Clean Code" dedicates an entire chapter to naming. Here are the key principles.</p><h2>Core Rules</h2><ul><li><strong>Use intention-revealing names:</strong> The name should answer why it exists and what it does</li><li><strong>Avoid disinformation:</strong> Don't call something a "list" if it's not a list</li><li><strong>Make meaningful distinctions:</strong> <code>source</code> and <code>destination</code> not <code>a1</code> and <code>a2</code></li><li><strong>Use pronounceable names:</strong> <code>generationTimestamp</code> not <code>genymdhms</code></li><li><strong>Use searchable names:</strong> Named constants instead of magic numbers</li><li><strong>Avoid encodings:</strong> No Hungarian notation, no member prefixes</li><li><strong>Class names are nouns:</strong> <code>Customer</code>, <code>Account</code>, <code>AddressParser</code></li><li><strong>Method names are verbs:</strong> <code>save()</code>, <code>deletePage()</code>, <code>postPayment()</code></li></ul><h2>Convert Names</h2><p>Use the <a href="%HUB%">case converter hub</a> to format names for any convention.</p>`,
  }),
  ja: build("ja", {
    title: "クリーンコードの命名原則：Robert C. Martinの教え",
    description: "Uncle Bobの『クリーンコード』から命名原則を学びましょう。意味のある名前、誤情報の回避、意図を明かすコード。",
    body: `<p>Robert C. Martinの『クリーンコード』は、命名に丸ごと1章を割いています。ここでは主要な原則を紹介します。</p><h2>基本ルール</h2><ul><li><strong>意図を明かす名前を使う:</strong> 名前は、なぜ存在し何をするのかに答えるべきです</li><li><strong>誤情報を避ける:</strong> リストでないものを「list」と呼ばない</li><li><strong>意味のある区別をつける:</strong> <code>a1</code>・<code>a2</code>ではなく<code>source</code>・<code>destination</code></li><li><strong>発音できる名前を使う:</strong> <code>genymdhms</code>ではなく<code>generationTimestamp</code></li><li><strong>検索できる名前を使う:</strong> マジックナンバーの代わりに名前付き定数を使う</li><li><strong>エンコーディングを避ける:</strong> ハンガリアン記法やメンバー接頭辞は使わない</li><li><strong>クラス名は名詞:</strong> <code>Customer</code>, <code>Account</code>, <code>AddressParser</code></li><li><strong>メソッド名は動詞:</strong> <code>save()</code>, <code>deletePage()</code>, <code>postPayment()</code></li></ul><h2>名前を変換する</h2><p><a href="%HUB%">ケース変換ハブ</a>で、あらゆる規則に合わせて名前をフォーマットしましょう。</p>`,
  }),
  de: build("de", {
    title: "Clean Code Naming Principles: Lektionen von Robert C. Martin",
    description: "Lernen Sie Namensgebungsprinzipien aus Clean Code von Uncle Bob. Aussagekräftige Namen, Vermeidung von Desinformation und absichtsoffenbarender Code.",
    body: `<p>Robert C. Martins „Clean Code" widmet der Benennung ein ganzes Kapitel. Hier sind die wichtigsten Prinzipien.</p><h2>Kernregeln</h2><ul><li><strong>Verwenden Sie absichtsoffenbarende Namen:</strong> Der Name sollte beantworten, warum etwas existiert und was es tut</li><li><strong>Vermeiden Sie Desinformation:</strong> Nennen Sie etwas nicht „list", wenn es keine Liste ist</li><li><strong>Treffen Sie sinnvolle Unterscheidungen:</strong> <code>source</code> und <code>destination</code> statt <code>a1</code> und <code>a2</code></li><li><strong>Verwenden Sie aussprechbare Namen:</strong> <code>generationTimestamp</code> statt <code>genymdhms</code></li><li><strong>Verwenden Sie suchbare Namen:</strong> Benannte Konstanten statt magischer Zahlen</li><li><strong>Vermeiden Sie Kodierungen:</strong> Keine ungarische Notation, keine Member-Präfixe</li><li><strong>Klassennamen sind Substantive:</strong> <code>Customer</code>, <code>Account</code>, <code>AddressParser</code></li><li><strong>Methodennamen sind Verben:</strong> <code>save()</code>, <code>deletePage()</code>, <code>postPayment()</code></li></ul><h2>Namen konvertieren</h2><p>Nutzen Sie den <a href="%HUB%">Case-Converter-Hub</a>, um Namen für jede Konvention zu formatieren.</p>`,
  }),
  es: build("es", {
    title: "Principios de nombres en Clean Code: Lecciones de Robert C. Martin",
    description: "Aprende los principios de nombres de Clean Code de Uncle Bob. Nombres significativos, evitar la desinformación y código que revela la intención.",
    body: `<p>«Clean Code» de Robert C. Martin dedica un capítulo entero a los nombres. Estos son los principios clave.</p><h2>Reglas fundamentales</h2><ul><li><strong>Usa nombres que revelen la intención:</strong> El nombre debe responder por qué existe y qué hace</li><li><strong>Evita la desinformación:</strong> No llames «list» a algo que no es una lista</li><li><strong>Haz distinciones significativas:</strong> <code>source</code> y <code>destination</code> en lugar de <code>a1</code> y <code>a2</code></li><li><strong>Usa nombres pronunciables:</strong> <code>generationTimestamp</code> en lugar de <code>genymdhms</code></li><li><strong>Usa nombres buscables:</strong> Constantes con nombre en lugar de números mágicos</li><li><strong>Evita las codificaciones:</strong> Sin notación húngara, sin prefijos de miembros</li><li><strong>Los nombres de clase son sustantivos:</strong> <code>Customer</code>, <code>Account</code>, <code>AddressParser</code></li><li><strong>Los nombres de método son verbos:</strong> <code>save()</code>, <code>deletePage()</code>, <code>postPayment()</code></li></ul><h2>Convertir nombres</h2><p>Usa el <a href="%HUB%">hub de conversión de mayúsculas y minúsculas</a> para dar formato a los nombres en cualquier convención.</p>`,
  }),
  pt: build("pt", {
    title: "Princípios de nomes em Clean Code: Lições de Robert C. Martin",
    description: "Aprenda os princípios de nomes do Clean Code do Uncle Bob. Nomes significativos, evitar desinformação e código que revela a intenção.",
    body: `<p>O "Clean Code" de Robert C. Martin dedica um capítulo inteiro à nomenclatura. Aqui estão os principais princípios.</p><h2>Regras fundamentais</h2><ul><li><strong>Use nomes que revelem a intenção:</strong> O nome deve responder por que existe e o que faz</li><li><strong>Evite a desinformação:</strong> Não chame algo de "list" se não for uma lista</li><li><strong>Faça distinções significativas:</strong> <code>source</code> e <code>destination</code> em vez de <code>a1</code> e <code>a2</code></li><li><strong>Use nomes pronunciáveis:</strong> <code>generationTimestamp</code> em vez de <code>genymdhms</code></li><li><strong>Use nomes pesquisáveis:</strong> Constantes nomeadas em vez de números mágicos</li><li><strong>Evite codificações:</strong> Sem notação húngara, sem prefixos de membros</li><li><strong>Nomes de classe são substantivos:</strong> <code>Customer</code>, <code>Account</code>, <code>AddressParser</code></li><li><strong>Nomes de método são verbos:</strong> <code>save()</code>, <code>deletePage()</code>, <code>postPayment()</code></li></ul><h2>Converter nomes</h2><p>Use o <a href="%HUB%">hub de conversão de maiúsculas e minúsculas</a> para formatar nomes em qualquer convenção.</p>`,
  }),
  fr: build("fr", {
    title: "Principes de nommage Clean Code : Leçons de Robert C. Martin",
    description: "Apprenez les principes de nommage de Clean Code par Uncle Bob. Noms significatifs, éviter la désinformation et code qui révèle l'intention.",
    body: `<p>Le « Clean Code » de Robert C. Martin consacre un chapitre entier au nommage. Voici les principes clés.</p><h2>Règles fondamentales</h2><ul><li><strong>Utilisez des noms qui révèlent l'intention :</strong> Le nom doit répondre à pourquoi il existe et ce qu'il fait</li><li><strong>Évitez la désinformation :</strong> N'appelez pas quelque chose « list » si ce n'est pas une liste</li><li><strong>Faites des distinctions significatives :</strong> <code>source</code> et <code>destination</code> plutôt que <code>a1</code> et <code>a2</code></li><li><strong>Utilisez des noms prononçables :</strong> <code>generationTimestamp</code> plutôt que <code>genymdhms</code></li><li><strong>Utilisez des noms recherchables :</strong> Des constantes nommées plutôt que des nombres magiques</li><li><strong>Évitez les encodages :</strong> Pas de notation hongroise, pas de préfixes de membres</li><li><strong>Les noms de classe sont des noms :</strong> <code>Customer</code>, <code>Account</code>, <code>AddressParser</code></li><li><strong>Les noms de méthode sont des verbes :</strong> <code>save()</code>, <code>deletePage()</code>, <code>postPayment()</code></li></ul><h2>Convertir les noms</h2><p>Utilisez le <a href="%HUB%">hub de conversion de casse</a> pour formater les noms selon n'importe quelle convention.</p>`,
  }),
};
