import type { Locale } from "@/i18n/routing";

export interface Article { title: string; description: string; body: string; }

export const meta = { slug: "code-readability-tips", date: "2026-06-01", readTime: 5 };

const p = (l: Locale, path: string) => (l === "en" ? path : `/${l}${path}`);
const build = (l: Locale, t: Article): Article => ({
  ...t,
  body: t.body
    .replaceAll("%HUB%", p(l, "/case-converter-online")),
});

export const article: Record<Locale, Article> = {
  en: build("en", {
    title: "10 Code Readability Tips Every Developer Should Know",
    description: "Improve code readability with these practical tips covering naming, formatting, comments, and structure.",
    body: `<p>Readable code reduces bugs, speeds up reviews, and makes maintenance easier. Here are 10 actionable tips.</p><ol><li><strong>Name things well:</strong> The #1 readability factor. Descriptive names eliminate the need for comments.</li><li><strong>Keep functions short:</strong> 20 lines max. Each function should do one thing.</li><li><strong>Follow your language's style guide:</strong> PEP 8 for Python, Airbnb for JS, etc.</li><li><strong>Consistent formatting:</strong> Use a formatter (Prettier, Black, gofmt) — never debate tabs vs spaces manually.</li><li><strong>Avoid deep nesting:</strong> Use early returns and guard clauses to flatten code.</li><li><strong>Write comments for "why", not "what":</strong> Code shows what; comments explain why.</li><li><strong>Use meaningful variable types:</strong> <code>isEnabled</code> (boolean) not <code>enabled</code> (could be string).</li><li><strong>Prefer positive conditions:</strong> <code>if (isValid)</code> not <code>if (!isInvalid)</code>.</li><li><strong>Group related code:</strong> Keep related logic together, separate concerns with blank lines.</li><li><strong>Delete dead code:</strong> Commented-out code is noise. Use version control instead.</li></ol><h2>Format Your Code</h2><p>Use the <a href="%HUB%">case converter hub</a> to ensure consistent naming conventions.</p>`,
  }),
  ja: build("ja", {
    title: "開発者が知るべき10のコード可読性Tips",
    description: "命名、フォーマット、コメント、構造をカバーする実践的なTipsでコードの可読性を向上させましょう。",
    body: `<p>読みやすいコードはバグを減らし、レビューを速め、保守を容易にします。すぐに実践できる10のTipsを紹介します。</p><ol><li><strong>適切に命名する:</strong> 可読性を決める最大の要因。説明的な名前があればコメントは不要になります。</li><li><strong>関数を短く保つ:</strong> 最大20行。各関数は1つのことだけを行うべきです。</li><li><strong>言語のスタイルガイドに従う:</strong> PythonならPEP 8、JSならAirbnbなど。</li><li><strong>一貫したフォーマット:</strong> フォーマッター(Prettier、Black、gofmt)を使い、タブvsスペースを手作業で議論しない。</li><li><strong>深いネストを避ける:</strong> 早期リターンとガード節でコードをフラットにする。</li><li><strong>コメントは「なぜ」を書き、「何を」は書かない:</strong> コードは「何を」を示し、コメントは「なぜ」を説明します。</li><li><strong>意味のある変数型を使う:</strong> <code>enabled</code>(文字列の可能性)ではなく<code>isEnabled</code>(真偽値)。</li><li><strong>肯定的な条件を優先する:</strong> <code>if (!isInvalid)</code>ではなく<code>if (isValid)</code>。</li><li><strong>関連するコードをまとめる:</strong> 関連ロジックを近くに置き、空行で関心事を分離する。</li><li><strong>デッドコードを削除する:</strong> コメントアウトされたコードはノイズです。代わりにバージョン管理を使いましょう。</li></ol><h2>コードをフォーマットする</h2><p><a href="%HUB%">ケース変換ハブ</a>で一貫した命名規則を保ちましょう。</p>`,
  }),
  de: build("de", {
    title: "10 Code-Lesbarkeits-Tipps für Entwickler",
    description: "Verbessern Sie die Code-Lesbarkeit mit diesen praktischen Tipps zu Benennung, Formatierung, Kommentaren und Struktur.",
    body: `<p>Lesbarer Code reduziert Fehler, beschleunigt Reviews und erleichtert die Wartung. Hier sind 10 umsetzbare Tipps.</p><ol><li><strong>Benennen Sie Dinge gut:</strong> Der wichtigste Lesbarkeitsfaktor. Aussagekräftige Namen machen Kommentare überflüssig.</li><li><strong>Halten Sie Funktionen kurz:</strong> Maximal 20 Zeilen. Jede Funktion sollte genau eine Sache tun.</li><li><strong>Folgen Sie dem Style Guide Ihrer Sprache:</strong> PEP 8 für Python, Airbnb für JS usw.</li><li><strong>Konsistente Formatierung:</strong> Verwenden Sie einen Formatter (Prettier, Black, gofmt) – diskutieren Sie nie manuell über Tabs vs. Leerzeichen.</li><li><strong>Vermeiden Sie tiefe Verschachtelung:</strong> Nutzen Sie frühe Returns und Guard Clauses, um den Code flach zu halten.</li><li><strong>Schreiben Sie Kommentare für das „Warum", nicht das „Was":</strong> Der Code zeigt das Was; Kommentare erklären das Warum.</li><li><strong>Verwenden Sie aussagekräftige Variablentypen:</strong> <code>isEnabled</code> (boolean) statt <code>enabled</code> (könnte ein String sein).</li><li><strong>Bevorzugen Sie positive Bedingungen:</strong> <code>if (isValid)</code> statt <code>if (!isInvalid)</code>.</li><li><strong>Gruppieren Sie zusammengehörigen Code:</strong> Halten Sie verwandte Logik zusammen, trennen Sie Belange durch Leerzeilen.</li><li><strong>Löschen Sie toten Code:</strong> Auskommentierter Code ist Rauschen. Nutzen Sie stattdessen die Versionsverwaltung.</li></ol><h2>Formatieren Sie Ihren Code</h2><p>Nutzen Sie den <a href="%HUB%">Case-Converter-Hub</a>, um konsistente Namenskonventionen sicherzustellen.</p>`,
  }),
  es: build("es", {
    title: "10 consejos de legibilidad de código que todo desarrollador debe conocer",
    description: "Mejora la legibilidad del código con estos consejos prácticos sobre nombres, formato, comentarios y estructura.",
    body: `<p>El código legible reduce errores, acelera las revisiones y facilita el mantenimiento. Aquí tienes 10 consejos prácticos.</p><ol><li><strong>Nombra bien las cosas:</strong> El factor de legibilidad número uno. Los nombres descriptivos eliminan la necesidad de comentarios.</li><li><strong>Mantén las funciones cortas:</strong> 20 líneas como máximo. Cada función debe hacer una sola cosa.</li><li><strong>Sigue la guía de estilo de tu lenguaje:</strong> PEP 8 para Python, Airbnb para JS, etc.</li><li><strong>Formato consistente:</strong> Usa un formateador (Prettier, Black, gofmt); nunca debatas tabs vs. espacios manualmente.</li><li><strong>Evita el anidamiento profundo:</strong> Usa retornos tempranos y cláusulas de guarda para aplanar el código.</li><li><strong>Escribe comentarios para el «porqué», no el «qué»:</strong> El código muestra el qué; los comentarios explican el porqué.</li><li><strong>Usa tipos de variable significativos:</strong> <code>isEnabled</code> (booleano) en lugar de <code>enabled</code> (podría ser un string).</li><li><strong>Prefiere condiciones positivas:</strong> <code>if (isValid)</code> en lugar de <code>if (!isInvalid)</code>.</li><li><strong>Agrupa el código relacionado:</strong> Mantén junta la lógica relacionada y separa responsabilidades con líneas en blanco.</li><li><strong>Elimina el código muerto:</strong> El código comentado es ruido. Usa el control de versiones en su lugar.</li></ol><h2>Formatea tu código</h2><p>Usa el <a href="%HUB%">hub de conversión de mayúsculas y minúsculas</a> para asegurar convenciones de nombres consistentes.</p>`,
  }),
  pt: build("pt", {
    title: "10 dicas de legibilidade de código que todo desenvolvedor deve conhecer",
    description: "Melhore a legibilidade do código com estas dicas práticas sobre nomenclatura, formatação, comentários e estrutura.",
    body: `<p>Código legível reduz erros, acelera as revisões e facilita a manutenção. Aqui estão 10 dicas práticas.</p><ol><li><strong>Nomeie bem as coisas:</strong> O fator de legibilidade número um. Nomes descritivos eliminam a necessidade de comentários.</li><li><strong>Mantenha as funções curtas:</strong> No máximo 20 linhas. Cada função deve fazer apenas uma coisa.</li><li><strong>Siga o guia de estilo da sua linguagem:</strong> PEP 8 para Python, Airbnb para JS, etc.</li><li><strong>Formatação consistente:</strong> Use um formatador (Prettier, Black, gofmt) — nunca debata tabs vs. espaços manualmente.</li><li><strong>Evite aninhamento profundo:</strong> Use retornos antecipados e cláusulas de guarda para achatar o código.</li><li><strong>Escreva comentários para o "porquê", não o "o quê":</strong> O código mostra o quê; os comentários explicam o porquê.</li><li><strong>Use tipos de variável significativos:</strong> <code>isEnabled</code> (booleano) em vez de <code>enabled</code> (pode ser uma string).</li><li><strong>Prefira condições positivas:</strong> <code>if (isValid)</code> em vez de <code>if (!isInvalid)</code>.</li><li><strong>Agrupe o código relacionado:</strong> Mantenha a lógica relacionada junta e separe responsabilidades com linhas em branco.</li><li><strong>Exclua código morto:</strong> Código comentado é ruído. Use o controle de versão em vez disso.</li></ol><h2>Formate seu código</h2><p>Use o <a href="%HUB%">hub de conversão de maiúsculas e minúsculas</a> para garantir convenções de nomenclatura consistentes.</p>`,
  }),
  fr: build("fr", {
    title: "10 conseils de lisibilité du code pour les développeurs",
    description: "Améliorez la lisibilité du code avec ces conseils pratiques sur le nommage, le formatage, les commentaires et la structure.",
    body: `<p>Un code lisible réduit les bugs, accélère les revues et facilite la maintenance. Voici 10 conseils concrets.</p><ol><li><strong>Nommez bien les choses :</strong> Le facteur de lisibilité numéro un. Des noms descriptifs rendent les commentaires inutiles.</li><li><strong>Gardez les fonctions courtes :</strong> 20 lignes maximum. Chaque fonction ne doit faire qu'une seule chose.</li><li><strong>Suivez le guide de style de votre langage :</strong> PEP 8 pour Python, Airbnb pour JS, etc.</li><li><strong>Formatage cohérent :</strong> Utilisez un formateur (Prettier, Black, gofmt) — ne débattez jamais des tabulations vs espaces manuellement.</li><li><strong>Évitez l'imbrication profonde :</strong> Utilisez des retours anticipés et des clauses de garde pour aplatir le code.</li><li><strong>Écrivez des commentaires pour le « pourquoi », pas le « quoi » :</strong> Le code montre le quoi ; les commentaires expliquent le pourquoi.</li><li><strong>Utilisez des types de variables explicites :</strong> <code>isEnabled</code> (booléen) plutôt que <code>enabled</code> (qui pourrait être une chaîne).</li><li><strong>Préférez les conditions positives :</strong> <code>if (isValid)</code> plutôt que <code>if (!isInvalid)</code>.</li><li><strong>Regroupez le code lié :</strong> Gardez la logique connexe ensemble, séparez les responsabilités par des lignes vides.</li><li><strong>Supprimez le code mort :</strong> Le code commenté est du bruit. Utilisez plutôt le contrôle de version.</li></ol><h2>Formatez votre code</h2><p>Utilisez le <a href="%HUB%">hub de conversion de casse</a> pour garantir des conventions de nommage cohérentes.</p>`,
  }),
};
