import type { Locale } from "@/i18n/routing";

export interface Article { title: string; description: string; body: string; }

export const meta = { slug: "function-naming-conventions", date: "2026-06-01", readTime: 4 };

const p = (l: Locale, path: string) => (l === "en" ? path : `/${l}${path}`);
const build = (l: Locale, t: Article): Article => ({
  ...t,
  body: t.body
    .replaceAll("%CAMEL%", p(l, "/camelcase-converter"))
    .replaceAll("%SNAKE%", p(l, "/snake-case-converter"))
    .replaceAll("%HUB%", p(l, "/case-converter-online")),
});

export const article: Record<Locale, Article> = {
  en: build("en", {
    title: "Function Naming Conventions: Verb Patterns for Clean Code",
    description: "Learn how to name functions using verb patterns: get, set, create, delete, validate, handle, and more.",
    body: `<p>Functions do things, so their names should start with verbs. The right verb pattern instantly communicates what a function does.</p><h2>Common Verb Patterns</h2><table><thead><tr><th>Verb</th><th>Purpose</th><th>Examples</th></tr></thead><tbody><tr><td><code>get</code></td><td>Retrieve data</td><td><code>getUserById</code>, <code>getTotal</code></td></tr><tr><td><code>set</code></td><td>Assign a value</td><td><code>setUserName</code>, <code>setTheme</code></td></tr><tr><td><code>create</code></td><td>Make something new</td><td><code>createOrder</code>, <code>createUser</code></td></tr><tr><td><code>delete/remove</code></td><td>Remove something</td><td><code>deleteUser</code>, <code>removeItem</code></td></tr><tr><td><code>update</code></td><td>Modify existing</td><td><code>updateProfile</code></td></tr><tr><td><code>validate</code></td><td>Check correctness</td><td><code>validateEmail</code></td></tr><tr><td><code>format</code></td><td>Transform display</td><td><code>formatDate</code>, <code>formatCurrency</code></td></tr><tr><td><code>parse</code></td><td>Extract structured data</td><td><code>parseJSON</code>, <code>parseCSV</code></td></tr><tr><td><code>handle</code></td><td>React to events</td><td><code>handleClick</code>, <code>handleError</code></td></tr><tr><td><code>fetch</code></td><td>Retrieve from remote</td><td><code>fetchUsers</code>, <code>fetchData</code></td></tr></tbody></table><h2>Convert</h2><p><a href="%CAMEL%">camelCase</a> for JS, <a href="%SNAKE%">snake_case</a> for Python. <a href="%HUB%">Hub</a>.</p>`,
  }),
  ja: build("ja", {
    title: "関数命名規則：クリーンコードのための動詞パターン",
    description: "get、set、create、delete、validateなどの動詞パターンで関数を命名する方法を学びましょう。",
    body: `<p>関数は何かを行うので、名前は動詞で始めるべきです。適切な動詞パターンを使えば、関数が何をするのか即座に伝わります。</p><h2>よく使う動詞パターン</h2><table><thead><tr><th>動詞</th><th>目的</th><th>例</th></tr></thead><tbody><tr><td><code>get</code></td><td>データを取得する</td><td><code>getUserById</code>, <code>getTotal</code></td></tr><tr><td><code>set</code></td><td>値を割り当てる</td><td><code>setUserName</code>, <code>setTheme</code></td></tr><tr><td><code>create</code></td><td>新しく作成する</td><td><code>createOrder</code>, <code>createUser</code></td></tr><tr><td><code>delete/remove</code></td><td>何かを削除する</td><td><code>deleteUser</code>, <code>removeItem</code></td></tr><tr><td><code>update</code></td><td>既存のものを変更する</td><td><code>updateProfile</code></td></tr><tr><td><code>validate</code></td><td>正しさを検証する</td><td><code>validateEmail</code></td></tr><tr><td><code>format</code></td><td>表示形式に変換する</td><td><code>formatDate</code>, <code>formatCurrency</code></td></tr><tr><td><code>parse</code></td><td>構造化データを抽出する</td><td><code>parseJSON</code>, <code>parseCSV</code></td></tr><tr><td><code>handle</code></td><td>イベントに反応する</td><td><code>handleClick</code>, <code>handleError</code></td></tr><tr><td><code>fetch</code></td><td>リモートから取得する</td><td><code>fetchUsers</code>, <code>fetchData</code></td></tr></tbody></table><h2>変換</h2><p>JSには<a href="%CAMEL%">camelCase</a>、Pythonには<a href="%SNAKE%">snake_case</a>。<a href="%HUB%">ハブはこちら</a>。</p>`,
  }),
  de: build("de", {
    title: "Funktions-Namenskonventionen: Verb-Muster für sauberen Code",
    description: "Lernen Sie, Funktionen mit Verb-Mustern zu benennen: get, set, create, delete, validate, handle und mehr.",
    body: `<p>Funktionen tun etwas, also sollten ihre Namen mit Verben beginnen. Das richtige Verb-Muster vermittelt sofort, was eine Funktion macht.</p><h2>Gängige Verb-Muster</h2><table><thead><tr><th>Verb</th><th>Zweck</th><th>Beispiele</th></tr></thead><tbody><tr><td><code>get</code></td><td>Daten abrufen</td><td><code>getUserById</code>, <code>getTotal</code></td></tr><tr><td><code>set</code></td><td>Einen Wert zuweisen</td><td><code>setUserName</code>, <code>setTheme</code></td></tr><tr><td><code>create</code></td><td>Etwas Neues erstellen</td><td><code>createOrder</code>, <code>createUser</code></td></tr><tr><td><code>delete/remove</code></td><td>Etwas entfernen</td><td><code>deleteUser</code>, <code>removeItem</code></td></tr><tr><td><code>update</code></td><td>Bestehendes ändern</td><td><code>updateProfile</code></td></tr><tr><td><code>validate</code></td><td>Korrektheit prüfen</td><td><code>validateEmail</code></td></tr><tr><td><code>format</code></td><td>Anzeige umwandeln</td><td><code>formatDate</code>, <code>formatCurrency</code></td></tr><tr><td><code>parse</code></td><td>Strukturierte Daten extrahieren</td><td><code>parseJSON</code>, <code>parseCSV</code></td></tr><tr><td><code>handle</code></td><td>Auf Ereignisse reagieren</td><td><code>handleClick</code>, <code>handleError</code></td></tr><tr><td><code>fetch</code></td><td>Aus der Ferne abrufen</td><td><code>fetchUsers</code>, <code>fetchData</code></td></tr></tbody></table><h2>Konvertieren</h2><p><a href="%CAMEL%">camelCase</a> für JS, <a href="%SNAKE%">snake_case</a> für Python. <a href="%HUB%">Hub</a>.</p>`,
  }),
  es: build("es", {
    title: "Convenciones de nombres de funciones: Patrones de verbos para código limpio",
    description: "Aprende a nombrar funciones con patrones de verbos: get, set, create, delete, validate, handle y más.",
    body: `<p>Las funciones hacen cosas, así que sus nombres deben comenzar con verbos. El patrón de verbo correcto comunica al instante lo que hace una función.</p><h2>Patrones de verbos comunes</h2><table><thead><tr><th>Verbo</th><th>Propósito</th><th>Ejemplos</th></tr></thead><tbody><tr><td><code>get</code></td><td>Recuperar datos</td><td><code>getUserById</code>, <code>getTotal</code></td></tr><tr><td><code>set</code></td><td>Asignar un valor</td><td><code>setUserName</code>, <code>setTheme</code></td></tr><tr><td><code>create</code></td><td>Crear algo nuevo</td><td><code>createOrder</code>, <code>createUser</code></td></tr><tr><td><code>delete/remove</code></td><td>Eliminar algo</td><td><code>deleteUser</code>, <code>removeItem</code></td></tr><tr><td><code>update</code></td><td>Modificar lo existente</td><td><code>updateProfile</code></td></tr><tr><td><code>validate</code></td><td>Comprobar la corrección</td><td><code>validateEmail</code></td></tr><tr><td><code>format</code></td><td>Transformar la visualización</td><td><code>formatDate</code>, <code>formatCurrency</code></td></tr><tr><td><code>parse</code></td><td>Extraer datos estructurados</td><td><code>parseJSON</code>, <code>parseCSV</code></td></tr><tr><td><code>handle</code></td><td>Reaccionar a eventos</td><td><code>handleClick</code>, <code>handleError</code></td></tr><tr><td><code>fetch</code></td><td>Recuperar desde remoto</td><td><code>fetchUsers</code>, <code>fetchData</code></td></tr></tbody></table><h2>Convertir</h2><p><a href="%CAMEL%">camelCase</a> para JS, <a href="%SNAKE%">snake_case</a> para Python. <a href="%HUB%">Hub</a>.</p>`,
  }),
  pt: build("pt", {
    title: "Convenções de nomes de funções: Padrões de verbos para código limpo",
    description: "Aprenda a nomear funções com padrões de verbos: get, set, create, delete, validate, handle e mais.",
    body: `<p>Funções fazem coisas, então seus nomes devem começar com verbos. O padrão de verbo certo comunica instantaneamente o que uma função faz.</p><h2>Padrões de verbos comuns</h2><table><thead><tr><th>Verbo</th><th>Propósito</th><th>Exemplos</th></tr></thead><tbody><tr><td><code>get</code></td><td>Recuperar dados</td><td><code>getUserById</code>, <code>getTotal</code></td></tr><tr><td><code>set</code></td><td>Atribuir um valor</td><td><code>setUserName</code>, <code>setTheme</code></td></tr><tr><td><code>create</code></td><td>Criar algo novo</td><td><code>createOrder</code>, <code>createUser</code></td></tr><tr><td><code>delete/remove</code></td><td>Remover algo</td><td><code>deleteUser</code>, <code>removeItem</code></td></tr><tr><td><code>update</code></td><td>Modificar o existente</td><td><code>updateProfile</code></td></tr><tr><td><code>validate</code></td><td>Verificar a correção</td><td><code>validateEmail</code></td></tr><tr><td><code>format</code></td><td>Transformar a exibição</td><td><code>formatDate</code>, <code>formatCurrency</code></td></tr><tr><td><code>parse</code></td><td>Extrair dados estruturados</td><td><code>parseJSON</code>, <code>parseCSV</code></td></tr><tr><td><code>handle</code></td><td>Reagir a eventos</td><td><code>handleClick</code>, <code>handleError</code></td></tr><tr><td><code>fetch</code></td><td>Recuperar de remoto</td><td><code>fetchUsers</code>, <code>fetchData</code></td></tr></tbody></table><h2>Converter</h2><p><a href="%CAMEL%">camelCase</a> para JS, <a href="%SNAKE%">snake_case</a> para Python. <a href="%HUB%">Hub</a>.</p>`,
  }),
  fr: build("fr", {
    title: "Conventions de nommage des fonctions : Patterns de verbes pour un code propre",
    description: "Apprenez à nommer les fonctions avec des patterns de verbes : get, set, create, delete, validate, handle et plus.",
    body: `<p>Les fonctions font des choses, donc leurs noms doivent commencer par des verbes. Le bon pattern de verbe indique instantanément ce que fait une fonction.</p><h2>Patterns de verbes courants</h2><table><thead><tr><th>Verbe</th><th>But</th><th>Exemples</th></tr></thead><tbody><tr><td><code>get</code></td><td>Récupérer des données</td><td><code>getUserById</code>, <code>getTotal</code></td></tr><tr><td><code>set</code></td><td>Affecter une valeur</td><td><code>setUserName</code>, <code>setTheme</code></td></tr><tr><td><code>create</code></td><td>Créer quelque chose de nouveau</td><td><code>createOrder</code>, <code>createUser</code></td></tr><tr><td><code>delete/remove</code></td><td>Supprimer quelque chose</td><td><code>deleteUser</code>, <code>removeItem</code></td></tr><tr><td><code>update</code></td><td>Modifier l'existant</td><td><code>updateProfile</code></td></tr><tr><td><code>validate</code></td><td>Vérifier l'exactitude</td><td><code>validateEmail</code></td></tr><tr><td><code>format</code></td><td>Transformer l'affichage</td><td><code>formatDate</code>, <code>formatCurrency</code></td></tr><tr><td><code>parse</code></td><td>Extraire des données structurées</td><td><code>parseJSON</code>, <code>parseCSV</code></td></tr><tr><td><code>handle</code></td><td>Réagir aux événements</td><td><code>handleClick</code>, <code>handleError</code></td></tr><tr><td><code>fetch</code></td><td>Récupérer à distance</td><td><code>fetchUsers</code>, <code>fetchData</code></td></tr></tbody></table><h2>Convertir</h2><p><a href="%CAMEL%">camelCase</a> pour JS, <a href="%SNAKE%">snake_case</a> pour Python. <a href="%HUB%">Hub</a>.</p>`,
  }),
};
