import type { Locale } from "@/i18n/routing";

export interface Article { title: string; description: string; body: string; }

export const meta = { slug: "naming-conventions-cheat-sheet", date: "2026-06-01", readTime: 4 };

const p = (l: Locale, path: string) => (l === "en" ? path : `/${l}${path}`);
const build = (l: Locale, t: Article): Article => ({
  ...t,
  body: t.body
    .replaceAll("%CAMEL%", p(l, "/camelcase-converter"))
    .replaceAll("%SNAKE%", p(l, "/snake-case-converter"))
    .replaceAll("%PASCAL%", p(l, "/pascal-case-converter"))
    .replaceAll("%KEBAB%", p(l, "/kebab-case-converter"))
    .replaceAll("%CONSTANT%", p(l, "/constant-case-converter"))
    .replaceAll("%HUB%", p(l, "/case-converter-online")),
});

export const article: Record<Locale, Article> = {
  en: build("en", {
    title: "Naming Conventions Cheat Sheet: Every Language at a Glance",
    description: "A one-page cheat sheet of naming conventions for JavaScript, Python, Java, C#, Go, Ruby, Rust, PHP, Swift, and Kotlin.",
    body: `<p>Bookmark this page. Every naming convention for every major language, in one table.</p><h2>The Master Table</h2><table><thead><tr><th>Language</th><th>Variables</th><th>Functions</th><th>Classes</th><th>Constants</th><th>Files</th></tr></thead><tbody><tr><td>JavaScript</td><td>camelCase</td><td>camelCase</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>camelCase/PascalCase</td></tr><tr><td>Python</td><td>snake_case</td><td>snake_case</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>snake_case</td></tr><tr><td>Java</td><td>camelCase</td><td>camelCase</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>PascalCase</td></tr><tr><td>C#</td><td>camelCase</td><td>PascalCase</td><td>PascalCase</td><td>PascalCase</td><td>PascalCase</td></tr><tr><td>Go</td><td>camelCase</td><td>camelCase/PascalCase</td><td>PascalCase</td><td>camelCase/PascalCase</td><td>snake_case</td></tr><tr><td>Ruby</td><td>snake_case</td><td>snake_case</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>snake_case</td></tr><tr><td>Rust</td><td>snake_case</td><td>snake_case</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>snake_case</td></tr><tr><td>PHP</td><td>camelCase</td><td>camelCase</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>PascalCase</td></tr><tr><td>Swift</td><td>camelCase</td><td>camelCase</td><td>PascalCase</td><td>camelCase</td><td>PascalCase</td></tr><tr><td>Kotlin</td><td>camelCase</td><td>camelCase</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>PascalCase</td></tr><tr><td>CSS</td><td>kebab-case</td><td>—</td><td>—</td><td>—</td><td>kebab-case</td></tr></tbody></table><h2>Convert Any Format</h2><p><a href="%CAMEL%">camelCase</a> · <a href="%SNAKE%">snake_case</a> · <a href="%PASCAL%">PascalCase</a> · <a href="%KEBAB%">kebab-case</a> · <a href="%CONSTANT%">CONSTANT_CASE</a> · <a href="%HUB%">All Formats</a></p>`,
  }),
  ja: build("ja", {
    title: "命名規則チートシート：全言語一覧",
    description: "JavaScript、Python、Java、C#、Go、Ruby、Rust、PHP、Swift、Kotlinの命名規則を1ページにまとめたチートシート。",
    body: `<p>このページをブックマークしましょう。すべての主要言語のあらゆる命名規則を1つのテーブルにまとめました。</p><h2>マスターテーブル</h2><table><thead><tr><th>言語</th><th>変数</th><th>関数</th><th>クラス</th><th>定数</th><th>ファイル</th></tr></thead><tbody><tr><td>JavaScript</td><td>camelCase</td><td>camelCase</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>camelCase/PascalCase</td></tr><tr><td>Python</td><td>snake_case</td><td>snake_case</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>snake_case</td></tr><tr><td>Java</td><td>camelCase</td><td>camelCase</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>PascalCase</td></tr><tr><td>C#</td><td>camelCase</td><td>PascalCase</td><td>PascalCase</td><td>PascalCase</td><td>PascalCase</td></tr><tr><td>Go</td><td>camelCase</td><td>camelCase/PascalCase</td><td>PascalCase</td><td>camelCase/PascalCase</td><td>snake_case</td></tr><tr><td>Ruby</td><td>snake_case</td><td>snake_case</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>snake_case</td></tr><tr><td>Rust</td><td>snake_case</td><td>snake_case</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>snake_case</td></tr><tr><td>PHP</td><td>camelCase</td><td>camelCase</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>PascalCase</td></tr><tr><td>Swift</td><td>camelCase</td><td>camelCase</td><td>PascalCase</td><td>camelCase</td><td>PascalCase</td></tr><tr><td>Kotlin</td><td>camelCase</td><td>camelCase</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>PascalCase</td></tr><tr><td>CSS</td><td>kebab-case</td><td>—</td><td>—</td><td>—</td><td>kebab-case</td></tr></tbody></table><h2>あらゆる形式に変換</h2><p><a href="%CAMEL%">camelCase</a> · <a href="%SNAKE%">snake_case</a> · <a href="%PASCAL%">PascalCase</a> · <a href="%KEBAB%">kebab-case</a> · <a href="%CONSTANT%">CONSTANT_CASE</a> · <a href="%HUB%">全フォーマット</a></p>`,
  }),
  de: build("de", {
    title: "Namenskonventionen Cheat Sheet: Alle Sprachen auf einen Blick",
    description: "Ein einseitiges Cheat Sheet der Namenskonventionen für JavaScript, Python, Java, C#, Go, Ruby, Rust, PHP, Swift und Kotlin.",
    body: `<p>Setzen Sie ein Lesezeichen auf diese Seite. Jede Namenskonvention jeder wichtigen Sprache in einer Tabelle.</p><h2>Die Master-Tabelle</h2><table><thead><tr><th>Sprache</th><th>Variablen</th><th>Funktionen</th><th>Klassen</th><th>Konstanten</th><th>Dateien</th></tr></thead><tbody><tr><td>JavaScript</td><td>camelCase</td><td>camelCase</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>camelCase/PascalCase</td></tr><tr><td>Python</td><td>snake_case</td><td>snake_case</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>snake_case</td></tr><tr><td>Java</td><td>camelCase</td><td>camelCase</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>PascalCase</td></tr><tr><td>C#</td><td>camelCase</td><td>PascalCase</td><td>PascalCase</td><td>PascalCase</td><td>PascalCase</td></tr><tr><td>Go</td><td>camelCase</td><td>camelCase/PascalCase</td><td>PascalCase</td><td>camelCase/PascalCase</td><td>snake_case</td></tr><tr><td>Ruby</td><td>snake_case</td><td>snake_case</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>snake_case</td></tr><tr><td>Rust</td><td>snake_case</td><td>snake_case</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>snake_case</td></tr><tr><td>PHP</td><td>camelCase</td><td>camelCase</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>PascalCase</td></tr><tr><td>Swift</td><td>camelCase</td><td>camelCase</td><td>PascalCase</td><td>camelCase</td><td>PascalCase</td></tr><tr><td>Kotlin</td><td>camelCase</td><td>camelCase</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>PascalCase</td></tr><tr><td>CSS</td><td>kebab-case</td><td>—</td><td>—</td><td>—</td><td>kebab-case</td></tr></tbody></table><h2>Beliebiges Format konvertieren</h2><p><a href="%CAMEL%">camelCase</a> · <a href="%SNAKE%">snake_case</a> · <a href="%PASCAL%">PascalCase</a> · <a href="%KEBAB%">kebab-case</a> · <a href="%CONSTANT%">CONSTANT_CASE</a> · <a href="%HUB%">Alle Formate</a></p>`,
  }),
  es: build("es", {
    title: "Cheat Sheet de convenciones de nombres: Todos los lenguajes",
    description: "Una hoja de referencia de una página con las convenciones de nombres de JavaScript, Python, Java, C#, Go, Ruby, Rust, PHP, Swift y Kotlin.",
    body: `<p>Guarda esta página en favoritos. Cada convención de nombres de cada lenguaje principal, en una sola tabla.</p><h2>La tabla maestra</h2><table><thead><tr><th>Lenguaje</th><th>Variables</th><th>Funciones</th><th>Clases</th><th>Constantes</th><th>Archivos</th></tr></thead><tbody><tr><td>JavaScript</td><td>camelCase</td><td>camelCase</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>camelCase/PascalCase</td></tr><tr><td>Python</td><td>snake_case</td><td>snake_case</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>snake_case</td></tr><tr><td>Java</td><td>camelCase</td><td>camelCase</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>PascalCase</td></tr><tr><td>C#</td><td>camelCase</td><td>PascalCase</td><td>PascalCase</td><td>PascalCase</td><td>PascalCase</td></tr><tr><td>Go</td><td>camelCase</td><td>camelCase/PascalCase</td><td>PascalCase</td><td>camelCase/PascalCase</td><td>snake_case</td></tr><tr><td>Ruby</td><td>snake_case</td><td>snake_case</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>snake_case</td></tr><tr><td>Rust</td><td>snake_case</td><td>snake_case</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>snake_case</td></tr><tr><td>PHP</td><td>camelCase</td><td>camelCase</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>PascalCase</td></tr><tr><td>Swift</td><td>camelCase</td><td>camelCase</td><td>PascalCase</td><td>camelCase</td><td>PascalCase</td></tr><tr><td>Kotlin</td><td>camelCase</td><td>camelCase</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>PascalCase</td></tr><tr><td>CSS</td><td>kebab-case</td><td>—</td><td>—</td><td>—</td><td>kebab-case</td></tr></tbody></table><h2>Convierte cualquier formato</h2><p><a href="%CAMEL%">camelCase</a> · <a href="%SNAKE%">snake_case</a> · <a href="%PASCAL%">PascalCase</a> · <a href="%KEBAB%">kebab-case</a> · <a href="%CONSTANT%">CONSTANT_CASE</a> · <a href="%HUB%">Todos los formatos</a></p>`,
  }),
  pt: build("pt", {
    title: "Cheat Sheet de convenções de nomes: Todas as linguagens",
    description: "Uma folha de referência de uma página com as convenções de nomes de JavaScript, Python, Java, C#, Go, Ruby, Rust, PHP, Swift e Kotlin.",
    body: `<p>Adicione esta página aos favoritos. Cada convenção de nomes de cada linguagem principal, em uma única tabela.</p><h2>A tabela mestra</h2><table><thead><tr><th>Linguagem</th><th>Variáveis</th><th>Funções</th><th>Classes</th><th>Constantes</th><th>Arquivos</th></tr></thead><tbody><tr><td>JavaScript</td><td>camelCase</td><td>camelCase</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>camelCase/PascalCase</td></tr><tr><td>Python</td><td>snake_case</td><td>snake_case</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>snake_case</td></tr><tr><td>Java</td><td>camelCase</td><td>camelCase</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>PascalCase</td></tr><tr><td>C#</td><td>camelCase</td><td>PascalCase</td><td>PascalCase</td><td>PascalCase</td><td>PascalCase</td></tr><tr><td>Go</td><td>camelCase</td><td>camelCase/PascalCase</td><td>PascalCase</td><td>camelCase/PascalCase</td><td>snake_case</td></tr><tr><td>Ruby</td><td>snake_case</td><td>snake_case</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>snake_case</td></tr><tr><td>Rust</td><td>snake_case</td><td>snake_case</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>snake_case</td></tr><tr><td>PHP</td><td>camelCase</td><td>camelCase</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>PascalCase</td></tr><tr><td>Swift</td><td>camelCase</td><td>camelCase</td><td>PascalCase</td><td>camelCase</td><td>PascalCase</td></tr><tr><td>Kotlin</td><td>camelCase</td><td>camelCase</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>PascalCase</td></tr><tr><td>CSS</td><td>kebab-case</td><td>—</td><td>—</td><td>—</td><td>kebab-case</td></tr></tbody></table><h2>Converta qualquer formato</h2><p><a href="%CAMEL%">camelCase</a> · <a href="%SNAKE%">snake_case</a> · <a href="%PASCAL%">PascalCase</a> · <a href="%KEBAB%">kebab-case</a> · <a href="%CONSTANT%">CONSTANT_CASE</a> · <a href="%HUB%">Todos os formatos</a></p>`,
  }),
  fr: build("fr", {
    title: "Cheat Sheet des conventions de nommage : Tous les langages",
    description: "Une fiche de référence d'une page des conventions de nommage pour JavaScript, Python, Java, C#, Go, Ruby, Rust, PHP, Swift et Kotlin.",
    body: `<p>Ajoutez cette page à vos favoris. Chaque convention de nommage de chaque langage majeur, dans un seul tableau.</p><h2>Le tableau de référence</h2><table><thead><tr><th>Langage</th><th>Variables</th><th>Fonctions</th><th>Classes</th><th>Constantes</th><th>Fichiers</th></tr></thead><tbody><tr><td>JavaScript</td><td>camelCase</td><td>camelCase</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>camelCase/PascalCase</td></tr><tr><td>Python</td><td>snake_case</td><td>snake_case</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>snake_case</td></tr><tr><td>Java</td><td>camelCase</td><td>camelCase</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>PascalCase</td></tr><tr><td>C#</td><td>camelCase</td><td>PascalCase</td><td>PascalCase</td><td>PascalCase</td><td>PascalCase</td></tr><tr><td>Go</td><td>camelCase</td><td>camelCase/PascalCase</td><td>PascalCase</td><td>camelCase/PascalCase</td><td>snake_case</td></tr><tr><td>Ruby</td><td>snake_case</td><td>snake_case</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>snake_case</td></tr><tr><td>Rust</td><td>snake_case</td><td>snake_case</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>snake_case</td></tr><tr><td>PHP</td><td>camelCase</td><td>camelCase</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>PascalCase</td></tr><tr><td>Swift</td><td>camelCase</td><td>camelCase</td><td>PascalCase</td><td>camelCase</td><td>PascalCase</td></tr><tr><td>Kotlin</td><td>camelCase</td><td>camelCase</td><td>PascalCase</td><td>SCREAMING_SNAKE</td><td>PascalCase</td></tr><tr><td>CSS</td><td>kebab-case</td><td>—</td><td>—</td><td>—</td><td>kebab-case</td></tr></tbody></table><h2>Convertir n'importe quel format</h2><p><a href="%CAMEL%">camelCase</a> · <a href="%SNAKE%">snake_case</a> · <a href="%PASCAL%">PascalCase</a> · <a href="%KEBAB%">kebab-case</a> · <a href="%CONSTANT%">CONSTANT_CASE</a> · <a href="%HUB%">Tous les formats</a></p>`,
  }),
};
